name = "NonconvexMultistart"
uuid = "11b12826-7e46-4acf-9706-be0a67f2add7"
authors = ["Mohamed Tarek <mohdibntarek@gmail.com> and contributors"]
version = "0.1.4"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Hyperopt = "93e5fe13-2215-51db-baaf-2e9a34fb2712"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonconvexCore = "035190e5-69f1-488f-aaab-becca2889735"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"

[compat]
ChainRulesCore = "1"
Hyperopt = "0.4"
LinearAlgebra = "1.12.0"
NonconvexCore = "1.5"
Parameters = "0.12, 0.13"
Reexport = "1"
Setfield = "1"
Sobol = "1"
julia = "1"

[extras]
NonconvexIpopt = "bf347577-a06d-49ad-a669-8c0e005493b8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["NonconvexIpopt", "Test"]
